version: "3.9"

services:
  app:
    platform: ${DEV_CONTAINER_PLATFORM:-linux/amd64}
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    working_dir: /app
    volumes:
      - .:/app
      - ${HARMONIE_DATA_DIR:-./data/harmonie/ml}:/mnt/harmonie-data-from-pds/ml
      - ${TMP_DIR:-./tmp}:/tmp
    environment:
      SRC_GRIB_ROOT_PATH: /mnt/harmonie-data-from-pds/ml
      REFS_ROOT_PATH: /app/refs
      SRC_GRIB_TEMP_PATH: ""
